### ISSUE TITLE
Spell practice mode check broken in IN when BGM is disabled

### ISSUE THREAD

**Issue by Priw8** [FrDarky/TouhouRPC#6]
This check: 
```cpp
if ((stageMode & STAGE_MODE_SPELL_PRACTICE_FLAG) != 0 || bgm_playing[0] != 'b')
```
is always true if the game was started with BGM disabled: the game doesn't update the music name string, so `bgm_playing` is just `"\0"` and as such doesn't start with `'b'`, no matter were you are in the game. This makes the program think that spell practice is active at all times when you're not in the main menu. Furthermore, if the game was started with BGM enabled and it was disabled later, the string in `bgm_playing` never gets updated and just holds the name of whatever song was last played, which can also lead to issues with this check.

Would there be any consequences of removing the `bgm_playing` check completely, and just leaving the flag check?

**Comment by TheBakaRem** [comment]
After some testing, it looks like removing the `bgm_playing` check does help when the BGM is disabled and fixes the issue, but it causes the display to behave a bit weirdly during them.

During the time before the boss spawns and starts her spell / after the boss dies, the game doesn't consider it as Stage Practice but as normal Practice.
This causes a small window of time where the display says "Practicing Stage X" instead of "Practicing a spell: X".
This is due to how the game works though, so I don't think it's as significant as this issue.
